### ISSUE TITLE
"there are more than one objects at vertex"

### ISSUE THREAD

**Issue by jsbtic** [morphometry/karambola#1]
Hi (and apologies if this is a silly question)

Is it possible to force karambola to ignore whether a vertex point is share by two or more objects (or perhaps it requires labeling)?

![mwe](https://user-images.githubusercontent.com/19534713/79393274-eb5a9880-7f6c-11ea-8c47-7fce3ed42183.png)

I'm trying to export a large isosurface from Matlab as `*.poly` file, and sometimes isosurface regions might be connected only by a common edge, (cf. the blue edge in the image). The resultant poly file will cause an error 

```bash
$ karambola -i isosurf.poly --no-labels
Converting Polyfile to Minkowski triangulation format ...     done
check surface ...
terminate called after throwing an instance of 'std::runtime_error'
  what():  your polyfile is damaged
there are more than one objects at vertex 6: (3, 2 , 1.55694305694)
neighbour unassigned = 0
surface.get_triangles_of_vertex(i).size() = 9
sum_of_triangles = 10
```
The problem can be circumvented using `'noshare'` option in Matlab's `isosurface` function, but it will produce huge amount of redundant vertices...

Here's MWE (for Matlab)

```Matlab
I = [0.7398, 0.7868, 0.8917, 0.3731, 0.4621, 0.7413, 0.3193, 0.3885, ...
    0.7073, 0.5036, 0.5580, 0.8095, 0.9468, 0.9478, 0.9563, 0.8541, ...
    0.8469, 0.9063, 0.7246, 0.5887, 0.7106, 0.6820, 0.4306, 0.5328, ...
    0.9726, 0.9720, 0.9694, 0.9491, 0.9152, 0.9162, 0.7689, 0.5137, ...
    0.5311, 0.5541, 0.1598, 0.1748];

I = reshape(I,3,4,3);
% threshold
th = 0.5;

% isosurface
[f,v] = isosurface(I,th);
[f2,v2,c] = isocaps(-I,th);

% join surface and surface caps
f3 = [f; f2+length(v(:,1))];
v3 = [v; v2];

%% export isosurface as *.POLY

filename = ['isosurf.poly'];
fid = fopen(filename, 'wt');

% vertices
fprintf(fid, 'POINTS\n'); 

N = size(v3,1);
for i = 1:N
    fprintf(fid,'%d: %.15f %.15f %.15f\n',[i, v3(i,:)]);
end

 N = size(f3,1);

% faces
fprintf(fid, 'POLYS\n');  
for i = 1:N
    fprintf(fid,'%d: %d %d %d\n',[i, f3(i,:)]);
%     fprintf(fid,'\n');
end

fprintf(fid, 'END\n');
fclose(fid);

% unix("karambola -i isosurf.poly --no-labels --reference_centroid")
```

and here's the resulting POLY file
```
POINTS
1: 1.653940550859013 1.000000000000000 1.000000000000000
2: 2.000000000000000 1.000000000000000 1.263825363825364
3: 1.883276870957807 2.000000000000000 1.000000000000000
4: 2.000000000000000 2.000000000000000 1.098492723492724
5: 2.000000000000000 2.135744985673353 1.000000000000000
6: 3.000000000000000 1.000000000000000 1.445842585738959
7: 3.000000000000000 2.000000000000000 1.556943056943057
8: 3.000000000000000 2.349749058971142 1.000000000000000
9: 3.980466630493760 1.000000000000000 1.000000000000000
10: 3.657817109144542 2.000000000000000 1.000000000000000
11: 4.000000000000000 2.000000000000000 1.455259026687598
12: 4.000000000000000 1.723945902943516 2.000000000000000
13: 3.561037318153068 2.000000000000000 2.000000000000000
14: 4.000000000000000 2.679060665362035 2.000000000000000
15: 4.000000000000000 1.137205173725590 3.000000000000000
16: 3.038711500423849 2.000000000000000 3.000000000000000
17: 3.087285994948077 3.000000000000000 3.000000000000000
18: 4.000000000000000 3.000000000000000 2.091620111731844
POLYS
1: 1 2 3
2: 3 2 4
3: 3 4 5
4: 2 6 4
5: 4 6 7
6: 8 5 7
7: 7 5 4
8: 9 10 6
9: 6 10 11
10: 6 11 7
11: 7 11 12
12: 7 12 13
13: 10 8 11
14: 11 8 7
15: 11 7 14
16: 14 7 13
17: 12 15 13
18: 13 15 16
19: 13 16 14
20: 14 16 17
21: 14 17 18
END
```

**Comment by SebastienCallens** [comment]
Hi! I have had similar issues with complex meshes in karambola. The problem is that the marching cubes algorithm (which is used to create the isosurface) sometimes results in non-manifold edges or non-manifold vertices. I recommend that you try to remove those from the final mesh, for example using meshlab.

**Comment by ManniDasMammut** [comment]
Hi!
Sorry for the late reply, I somehow did not get notified about this issue.

I had a look at your poly file and as karambola displays, there are more than one object at a vertex.
This is not allowed, since some of the tensors cannot be calculated in this case.

I realized, that in error message of karambola, the vertex number is shifted by one, so in your case, the broken vertex is number 7.
(you can see this as well that edge 7->11 is used in four triangles)
I tried to sketch it, see image.

![sketch-small2](https://user-images.githubusercontent.com/38250701/81733564-82ded880-9492-11ea-9523-ab12754a66d5.jpg)


If two objects share a vertex, you have to double that vertex and use a different one for each object.
In the current implementation, we are not able to ignore this, since it will lead to erroneous results.

**Comment by jsbtic** [comment]
Dear both,
  much obliged. I was originally confused with the term "object" as I though Karambola assumes only one object per poly file unless labels are given. Instead Karambola determines distinct objects by connection(?). If two subsets of vertices are connected only by two or one vertices (non-manifold) Karambola assigns those two subsets as two different objects? 

For instance here:
![octahedron](https://user-images.githubusercontent.com/19534713/82072374-8a3ef580-96cf-11ea-885d-cf5293558301.png)
on left case Karambola runs without problems, and on the case on the right it detects that the two tetrahedrons are different objects, and complains that those objects share vertices.

 I'm just wondering that if this is the case, that Karambola can essential find the non-manifold vertices, it would seem rather short step to copy those vertices to make them unique for each object... But I do see the point that it's the users responsibility to provide poly file with only manifold objects. (Unfortunately there doesn't seem to be ready implementation in Matlab to check for the non-manifolds)

PS. Here's the code to create the figure
```Matlab
% create low resolution sphere -> octahedron
N = 3;
d = linspace(-3,3,N);
[X,Y,Z] = meshgrid(d,d,d);
V = sqrt(X.^2+Y.^2+Z.^2);


fv = isosurface(X,Y,Z,V)

% second configuration - non manifold
f2 = [1 2 3; 1 3 4; 1 4 2; 3 2 4; 2 4 5; 4 2 6; 2 5 6; 5 4 6]

subplot(1,2,1)
patch(fv,'FaceColor','k','FaceAlpha',0.3,'EdgeColor','k','LineWidth',2); 
view(-10,10); axis equal;

subplot(1,2,2)
patch('Faces',f2(1:4,:),'Vertices',v,'FaceColor','b','FaceAlpha',0.6,'EdgeColor','k','LineWidth',2); 
patch('Faces',f2(5:end,:),'Vertices',v,'FaceColor','r','FaceAlpha',0.6,'EdgeColor','k','LineWidth',2); 
view(-10,10); axis equal;


%% export to karambola

filename = ['isosurf.poly'];
fid = fopen(filename, 'wt');

% export header
fprintf(fid, 'POINTS\n');  % header

% vertive
N = size(fv.vertices,1)
for i = 1:N
    fprintf(fid,'%d: %.15f %.15f %.15f\n',[i, fv.vertices(i,:)]);
%     fprintf(fid,'\n');
end

N = size(fv.faces,1);

fprintf(fid, 'POLYS\n');  % header
for i = 1:N
    fprintf(fid,'%d: %5d %5d %5d \n',[i, fv.faces(i,:)]);
%     fprintf(fid,'\n');
end
fprintf(fid, 'END\n');  % header

fclose(fid);
```
and the polyfile
```
POINTS
1: 0.000000000000000 0.000000000000000 -2.572095449239783
2: 0.000000000000000 -2.572095449239783 0.000000000000000
3: -2.572095449239783 0.000000000000000 0.000000000000000
4: 0.000000000000000 2.572095449239783 0.000000000000000
5: 2.572095449239783 0.000000000000000 0.000000000000000
6: 0.000000000000000 0.000000000000000 2.572095449239783
POLYS
1:     1     2     3 
2:     1     3     4 
3:     1     5     2 
4:     1     4     5 
5:     2     6     3 
6:     3     6     4 
7:     2     5     6 
8:     5     4     6 
END
```

**Comment by skapfer** [comment]
Dear Johannes,

you are right, the wording is a little confusing here.

I'm not sure it is trivial to duplicate those points, I think there's actually an
ambuiguity about the topology of the object in these points which needs to be
resolved one way or the other.  It's been a few years, I don't fully remember.

@Fabian Do you recall the details?

Sebastian

On Fri, May 15, 2020 at 09:30:35AM -0700, Johannes Haataja wrote:
> Dear both,
>   much obliged. I was originally confused with the term "object" as I though Karambola assumes only one object per poly file unless labels are given. Instead Karambola determines distinct objects by connection(?). If two subsets of vertices are connected only by two or one vertices (non-manifold) Karambola assigns those two subsets as two different objects? 
> 
> For instance here:
> ![octahedron](https://user-images.githubusercontent.com/19534713/82072374-8a3ef580-96cf-11ea-885d-cf5293558301.png)
> on left case Karambola runs without problems, and on the case on the right it detects that the two tetrahedrons are different objects, and complains that those objects share vertices.
> 
>  I'm just wondering that if this is the case, that Karambola can essential find the non-manifold vertices, it would seem rather short step to copy those vertices to make them unique for each object... But I do see the point that it's the users responsibility to provide poly file with only manifold objects. (Unfortunately there doesn't seem to be ready implementation in Matlab to check for the non-manifolds)
> 
> PS. Here's the code to create the figure
> ```Matlab
> % create low resolution sphere -> octahedron
> N = 3;
> d = linspace(-3,3,N);
> [X,Y,Z] = meshgrid(d,d,d);
> V = sqrt(X.^2+Y.^2+Z.^2);
> 
> 
> fv = isosurface(X,Y,Z,V)
> 
> % second configuration - non manifold
> f2 = [1 2 3; 1 3 4; 1 4 2; 3 2 4; 2 4 5; 4 2 6; 2 5 6; 5 4 6]
> 
> subplot(1,2,1)
> patch(fv,'FaceColor','k','FaceAlpha',0.3,'EdgeColor','k','LineWidth',2); 
> view(-10,10); axis equal;
> 
> subplot(1,2,2)
> patch('Faces',f2(1:4,:),'Vertices',v,'FaceColor','b','FaceAlpha',0.6,'EdgeColor','k','LineWidth',2); 
> patch('Faces',f2(5:end,:),'Vertices',v,'FaceColor','r','FaceAlpha',0.6,'EdgeColor','k','LineWidth',2); 
> view(-10,10); axis equal;
> 
> 
> %% export to karambola
> 
> filename = ['isosurf.poly'];
> fid = fopen(filename, 'wt');
> 
> % export header
> fprintf(fid, 'POINTS\n');  % header
> 
> % vertive
> N = size(fv.vertices,1)
> for i = 1:N
>     fprintf(fid,'%d: %.15f %.15f %.15f\n',[i, fv.vertices(i,:)]);
> %     fprintf(fid,'\n');
> end
> 
> N = size(fv.faces,1);
> 
> fprintf(fid, 'POLYS\n');  % header
> for i = 1:N
>     fprintf(fid,'%d: %5d %5d %5d \n',[i, fv.faces(i,:)]);
> %     fprintf(fid,'\n');
> end
> fprintf(fid, 'END\n');  % header
> 
> fclose(fid);
> ```
> and the polyfile
> ```
> POINTS
> 1: 0.000000000000000 0.000000000000000 -2.572095449239783
> 2: 0.000000000000000 -2.572095449239783 0.000000000000000
> 3: -2.572095449239783 0.000000000000000 0.000000000000000
> 4: 0.000000000000000 2.572095449239783 0.000000000000000
> 5: 2.572095449239783 0.000000000000000 0.000000000000000
> 6: 0.000000000000000 0.000000000000000 2.572095449239783
> POLYS
> 1:     1     2     3 
> 2:     1     3     4 
> 3:     1     5     2 
> 4:     1     4     5 
> 5:     2     6     3 
> 6:     3     6     4 
> 7:     2     5     6 
> 8:     5     4     6 
> END
> ```
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/morphometry/karambola/issues/1#issuecomment-629356848

-- 
Best regards,               | Theoretische Physik 1, 02.573
  Sebastian Kapfer          | FAU Erlangen
                            | Staudtstr. 7, 91058 Erlangen, Germany
                            | Phone: +49.160.9577.6436
                            | https://theorie1.physik.fau.de/people/skapfer/
                            | GPG: ED891239B22DD0D516F2D9247554541B84406C3F

**Comment by jsbtic** [comment]
Dear Sebastian,
           after some trial and error I see that you are right about the ambiguity. Since[ "Non-manifold geometry is defined as any edge shared by more than two faces"](https://support.shapeways.com/hc/en-us/articles/360007107674-Tips-for-successful-modeling) it's rather easy to form a set of edges from the set of faces and check which edges present more than two times
```Matlab
% list of faces
f = [1     2     3
     1     3     4
     1     4     2
     3     2     4
     2     4     5
     4     2     6
     2     5     6
     5     4     6];

% create edge list from face list - assumes triangulation
el = reshape(f(:,[1 2 2 3 1 3]),[],2);
el = sort(el,2);

% find identical rows (edges) that occur more than twice
a = sortrows(el);

% find rows that are identical with row+2
I = find(sum(a == circshift(a,2,1),2)==2);

% unique non-manifold edge(s)
de = unique(a(I,:),'rows')
```
However one must then label the remaining vertices to N objects based on connectivity when manifold vertices are excluded, check to which M objects each non-manifold vertex belongs and decide in which of those M-1 objects you'll have to rename those vertices.

But even such connectiveness based labeling would fail for topologies like Devil's doughnut:
![Devil's doughnut](https://user-images.githubusercontent.com/19534713/82118907-0c7ff600-9772-11ea-81b7-956449acf024.png)
so it's not an easy problem to solve. 

I guess it's easier to try to find a modification of the marching cube algorithm that doesn't create non-manifold topologies. There's seems to be [[1](https://ieeexplore.ieee.org/document/7851184)], [[2](https://link.springer.com/article/10.1186/s13173-019-0086-6)], but alas! No implementations available yet.

**Comment by skapfer** [comment]
Dear Johannes,

we will try to add better error messages. I don't think it would make much sense
to have Karambola modify the mesh, there's probably better tools available to do
that.

Cheers,
  Sebastian

On Sat, May 16, 2020 at 05:02:42AM -0700, Johannes Haataja wrote:
> Dear Sebastian,
>            after some trial and error I see that you are right about the ambiguity. Since[ "Non-manifold geometry is defined as any edge shared by more than two faces"](https://support.shapeways.com/hc/en-us/articles/360007107674-Tips-for-successful-modeling) it's rather easy to form a set of edges from the set of faces and check which edges present more than two times
> ```Matlab
> % list of faces
> f = [1     2     3
>      1     3     4
>      1     4     2
>      3     2     4
>      2     4     5
>      4     2     6
>      2     5     6
>      5     4     6];
> 
> % create edge list from face list - assumes triangulation
> el = reshape(f(:,[1 2 2 3 1 3]),[],2);
> el = sort(el,2);
> 
> % find identical rows (edges) that occur more than twice
> a = sortrows(el);
> 
> % find rows that are identical with row+2
> I = find(sum(a == circshift(a,2,1),2)==2);
> 
> % unique non-manifold edge(s)
> de = unique(a(I,:),'rows')
> ```
> However one must then label the remaining vertices to N objects based on connectivity when manifold vertices are excluded, check to which M objects each non-manifold vertex belongs and decide in which of those M-1 objects you'll have to rename those vertices.
> 
> But even such connectiveness based labeling would fail for topologies like Devil's doughnut:
> ![Devil's doughnut](https://user-images.githubusercontent.com/19534713/82118907-0c7ff600-9772-11ea-81b7-956449acf024.png)
> so it's not an easy problem to solve. 
> 
> I guess it's easier to try to find a modification of the marching cube algorithm that doesn't create non-manifold topologies. There's seems to be [[1](https://ieeexplore.ieee.org/document/7851184)], [[2](https://link.springer.com/article/10.1186/s13173-019-0086-6)], but alas! No implementations available yet.
> 
> 
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/morphometry/karambola/issues/1#issuecomment-629635067

-- 
Best regards,               | Theoretische Physik 1, 02.573
  Sebastian Kapfer          | FAU Erlangen
                            | Staudtstr. 7, 91058 Erlangen, Germany
                            | Phone: +49.160.9577.6436
                            | https://theorie1.physik.fau.de/people/skapfer/
                            | GPG: ED891239B22DD0D516F2D9247554541B84406C3F

**Comment by SebastienCallens** [comment]
Hi Johannes,

Have you considered using meshlab (open-source) to deal with non-manifold edges and vertices? This tool has some great implementations to detect those features and remove or "fix" them. You could consider importing your marching cubes mesh from Matlab into meshlab, and then export the "fixed" mesh to karambola. I have also struggled with non-manifold features, and meshlab did the trick for me.

All the best,
Sebastien

**Comment by jsbtic** [comment]
Hi Sebastien,
          your comments were very helpful. I hadn't heard about non-manifolds before, so your suggestion was crucial in understanding the problem. Meshlab is a fine program. For me the issue is rather that when one is working with multiple files, it is preferable to use GUI as little as possible in order to automate things.

Therefore I ended up writing a short python script for [Blender](https://www.blender.org/) to fix the non-manifolds. (Again, thanks to you because I hadn't considered previously that Blender could also have this feature)

`fix_non_manifolds.py`:
```Python
import bpy
import os

# variables
fin = 'myfile.stl'
fout = fin.replace('.stl','.obj')

# import the stl file
bpy.ops.import_mesh.stl(filepath=fin)

# clean non-manifolds
bpy.ops.mesh.print3d_clean_non_manifold()

# export as wavefront
bpy.ops.export_scene.obj(filepath=fout,use_selection=True,use_triangles=True)
```
The script can the be run with Blender in non-GUI mode from the command line
```bash
blender --background --python fix_non_manifolds.py
```
I'm exporting the results as wavefront (`*.obj`) rather than `*.stl` as former is in ASCII, and can then be easily parsed to poly file using bash & regex.

My best,
      Johannes

**Comment by ManniDasMammut** [comment]
Hi!
thanks for your comments, I will add a better error message to karambola.
I started a troubleshooting section on the karambola webpage and linked this issu:
https://morphometry.org/software/karambola/#troubleshooting
Best,
Fabian

**Comment by jsbtic** [comment]
Hi,
  and much obliged Fabian. It's always a delight when a program is been kept up to date, which is not given, since in academia authors often lose interest after a publication is made. 

My best,
     Johannes
